from __future__ import annotations

from dataclasses import replace

from fastapi import APIRouter

from models.schemas import MessageRequest, MessageResponse
from interpreter.llm import interpret_message
from interpreter.signals import map_signals_to_event
from machine.states import State
from machine.events import Event
from machine.context import DecisionContext
from machine.actions import Action
from machine.transition import transition
from executor import execute
import store

router = APIRouter()

# Maximum system-event iterations to prevent infinite loops
_MAX_SYSTEM_ITERATIONS = 3


def _confirmation_required(ctx: DecisionContext) -> bool:
    """Mirror of the guard in transition.py.

    Used by the system-event loop to decide whether to auto-confirm.
    Must stay in sync with machine/transition.py::_confirmation_required.
    """
    if len(ctx.responses) < ctx.min_participants:
        return True
    if len(ctx.uncertainties) > 0:
        return True
    if len(ctx.objections) > 0:
        return True
    if ctx.requires_explicit_approval:
        return True
    if ctx.requires_initiator_approval:
        return True
    return False


def _derive_system_event(
    state: State,
    context: DecisionContext,
) -> Event | None:
    """Derive a system event from the current state.

    System events allow the machine to continue processing
    without waiting for external input. They are generated by
    the system, NOT by the LLM.

    Returns None if no system event should fire.
    """
    if state == State.AGGREGATING:
        return Event.AGGREGATION_COMPLETED

    if state == State.VALIDATING:
        return Event.VALIDATION_COMPLETED

    # Spec v2.8.1: auto-finalize if no confirmation required
    if state == State.DECIDING and not _confirmation_required(context):
        return Event.DECISION_CONFIRMED

    return None


@router.post("/message", response_model=MessageResponse)
def post_message(req: MessageRequest):
    """Single endpoint for the decision loop.

    Flow:
    1. Load state + context
    2. Update context with new message
    3. Interpret message → Signals
    4. Map signals → Event
    5. Transition loop:
       a. transition(state, event, context)
       b. Check for system event
       c. If system event → loop (max _MAX_SYSTEM_ITERATIONS)
    6. Execute all collected actions → reply
    7. Persist updated state
    8. Return response
    """
    # 1. Load
    state, context = store.load(req.decision_id)

    # 2. Update context with the incoming message
    if not context.question:
        context = replace(context, question=req.message)

    # Append response from participant
    responses = dict(context.responses)
    participant_responses = list(responses.get(req.participant, []))
    participant_responses.append(req.message)
    responses[req.participant] = participant_responses
    context = replace(context, responses=responses)

    # Ensure participant is tracked
    if req.participant not in context.participants:
        participants = list(context.participants)
        participants.append(req.participant)
        context = replace(context, participants=participants)

    # 3. Interpret → Signals
    signals = interpret_message(req.message)

    # 4. Merge signal data into context
    context = replace(
        context,
        preferences=context.preferences + signals.preferences,
        constraints=context.constraints + signals.constraints,
        uncertainties=context.uncertainties + signals.uncertainties,
        objections=context.objections + signals.objections,
    )

    # 5. Signals → Event (initial, user-driven)
    event = map_signals_to_event(signals)

    # 6. Transition loop (user event + system events)
    all_actions: list[Action] = []

    next_state, actions, context = transition(state, event, context)
    all_actions.extend(actions)

    # System event loop — allow internal state progression
    for _ in range(_MAX_SYSTEM_ITERATIONS):
        system_event = _derive_system_event(next_state, context)
        if system_event is None:
            break

        prev_state = next_state
        next_state, actions, context = transition(next_state, system_event, context)
        all_actions.extend(actions)

        # If state didn't change, stop (prevent spin)
        if next_state == prev_state:
            break

    # 7. Execute actions → reply
    reply = execute(all_actions, context)

    # 8. Persist
    store.save(req.decision_id, next_state, context)

    return MessageResponse(
        decision_id=req.decision_id,
        state=next_state.value,
        reply=reply,
        actions_executed=[a.type.value for a in all_actions],
    )
